export const ACADEMICS_DEPARTMENTS = [
  "Biotechnology Engineering",
  "Master Of Business Administration",
  "Master of Computer Application",
  "Bachelor of Computer Application",
  "Electronics and Instrumentation Engineering",
  "MTech Environmental Engineering",
  "MTech Structural Engineering",
  "Textile Engineering",
  "Chemical Engineering",
  "Civil Engineering",
  "Computer Science and Engineering",
  "Electronics and Communication Engineering",
  "Electrical and Electronics Engineering",
  "Information Science and Engineering",
  "Mechanical Engineering",
  "First Year",
  "Computer Science and Engineering (Data Science)",
  "Computer Science and Business Systems",
  "Computer Science and Design",
  "Artificial Intelligence and Machine Learning",
  "MBBS",
  "Doctor of Pharmacy",
  "Bachelor of Commerce",
  "Diploma in Pharmacy",
  "Bachelor of Science",
  "Science",
  "Commerce",
  "Bachelor of Business Administration",
  "Department 1",
  "Department 2",
  "Department 3",
  "Master of Pharmacy",
  "Bachelor of Pharmacy",
  "Bachelor of Arts",
  "No Department",
];